name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27.1.2
          elixir-version: 1.17.3

      - name: Install dependencies
        run: |
          mix deps.get
          mix deps.compile

      - name: Check mix format
        run: mix format --check-formatted

      - name: Start Typesense
        run: docker run -d -p 8108:8108 typesense/typesense:26.0 --data-dir /tmp --api-key=hexdocs

      - name: Run tests
        run: |
          mix test --include typesense
