name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 25.3.1
          elixir-version: 1.14.2

      - name: Install dependencies
        run: |
          mix deps.get
          mix deps.compile

      - name: Check mix format
        run: mix format --check-formatted

      - name: Run tests
        run: |
          mix test
